import * as XLSX from "xlsx";

export const hoje = new Date();
export const hojeISO = hoje.toISOString().slice(0, 10);

export const STATUS_OPC = ["Não Contatado", "Em Cobrança", "Sem Retorno", "Prometeu Pagar", "Pago Aguard. Baixa", "Em Permuta", "Encerrado", "Incobrável / Baixa por Perda"];
export const ENCAMINHAR_OPC = [
  { value: "", label: "Sem encaminhamento" },
  { value: "verificacao", label: "→ Verificar Pagamento" },
  { value: "protesto", label: "→ Solicitar Protesto" },
  { value: "assessoria", label: "→ Encaminhar para Assessoria" },
];
export const CONTATO_OPC = ["Ligação", "WhatsApp", "E-mail", "Presencial", "Mensagem Interna"];
export const VERIF_RESP = ["Confirmado", "Não localizado", "Baixado", "Erro", "Duplicidade", "Devolver para cobrança"];
export const PROT_RESP = ["Aprovado", "Reprovado", "Devolver para cobrança"];
export const FAIXAS_ATRASO = [
  { label: "Todos", value: 0 },
  { label: "7+ dias", value: 7 },
  { label: "15+ dias", value: 15 },
  { label: "30+ dias", value: 30 },
  { label: "60+ dias", value: 60 },
  { label: "90+ dias", value: 90 },
  { label: "180+ dias", value: 180 },
];

const INVISIBLE_DEDUPE = /[\u200B\u200C\u200D\u2060\u2063]/g;
const DOC_TOKENS = new Set(["NF", "NFE", "NFSE", "FAT", "TC", "EB", "CTE", "DUP", "DUPL", "DUPLICATA", "TITULO", "PARCELA", "REC"]);
const FINR1253_TITLE_TOKENS = new Set(["FAT", "REC", "NF", "NFE"]);

export function fmtD(d) { if (!d) return "—"; const dt = new Date(`${d}T00:00:00`); return Number.isNaN(dt.getTime()) ? "—" : dt.toLocaleDateString("pt-BR"); }
export function fmtM(v) { return Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
export function num(v) { if (typeof v === "number") return Number.isFinite(v) ? v : 0; const raw = String(v ?? "").trim().replace(/[R$\s]/g, ""); if (!raw) return 0; const normalized = raw.replace(/\./g, "").replace(/,/, "."); return Number.parseFloat(normalized) || 0; }
export function dateISO(v) { if (v == null || v === "") return ""; if (typeof v === "number") { const ssf = XLSX.SSF || XLSX.default?.SSF; const p = ssf?.parse_date_code(v); if (!p) return ""; const y = p.y; const m = String(p.m).padStart(2, "0"); const d = String(p.d).padStart(2, "0"); return `${y}-${m}-${d}`; } const raw = String(v).trim(); const pts = raw.split(/[-/]/); if (pts.length === 3) { const iso = pts[0].length === 4 ? `${pts[0]}-${pts[1].padStart(2, "0")}-${pts[2].padStart(2, "0")}` : `${pts[2]}-${pts[1].padStart(2, "0")}-${pts[0].padStart(2, "0")}`; return /^\d{4}-\d{2}-\d{2}$/.test(iso) ? iso : ""; } return ""; }
export function diffDias(d) { if (!d) return 0; const r = Math.floor((hoje - new Date(`${d}T00:00:00`)) / 86400000); return r > 0 ? r : 0; }
export function promAlerta(ds) { if (!ds) return null; const diff = Math.floor((new Date(`${ds}T00:00:00`) - new Date(`${hojeISO}T00:00:00`)) / 86400000); if (diff < 0) return { label: "Vencida", cor: "#dc2626" }; if (diff === 0) return { label: "Vence hoje", cor: "#ea580c" }; if (diff <= 3) return { label: `${diff}d`, cor: "#ea580c" }; return null; }
export function prioLabel(diasAtraso, qtdPromessas) { if (diasAtraso > 90 || qtdPromessas >= 3) return "CRÍTICO"; if (diasAtraso > 30 || qtdPromessas >= 2) return "ALTO"; if (diasAtraso > 0 || qtdPromessas >= 1) return "MÉDIO"; return "BAIXO"; }
export function prioCor(l) { return l === "CRÍTICO" ? "#ef4444" : l === "ALTO" ? "#f97316" : l === "MÉDIO" ? "#eab308" : "#64748b"; }
export function promessaClassif(qtd) { if (qtd >= 3) return { label: "Crítico", cor: "#ef4444" }; if (qtd === 2) return { label: "Médio", cor: "#f97316" }; if (qtd === 1) return { label: "Baixo", cor: "#3b82f6" }; return { label: "Nenhuma", cor: "#64748b" }; }
export function sugestaoEncaminhamento(diasAtraso, valor) { if (diasAtraso > 900) return { label: "Perda", cor: "#991b1b" }; if (diasAtraso > 180 || (diasAtraso > 90 && valor > 5000)) return { label: "Protesto", cor: "#b91c1c" }; if (diasAtraso > 90) return { label: "Protesto/Assessoria", cor: "#dc2626" }; if (diasAtraso > 60) return { label: "Assessoria", cor: "#ef4444" }; return null; }
export function normText(v) { return String(v ?? "").trim().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\./g, "").replace(/\s+/g, " "); }
function normHeader(v) { return String(v ?? "").trim().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/^\uFEFF/, "").replace(/[^A-Z0-9]/g, ""); }
function normH(v) { return String(v ?? "").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[.\-_°ºª]/g, " ").replace(/\s+/g, " ").trim(); }
function normToken(v) { return String(v ?? "").trim().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^A-Z0-9]/g, ""); }
function isDocToken(v) { const n = normToken(v); return DOC_TOKENS.has(n) || /^NF\d*$/.test(n) || /^NFE\d*$/.test(n) || /^FAT\d*$/.test(n) || /^REC\d*$/.test(n); }
function isFinr1253TitleToken(v) { return FINR1253_TITLE_TOKENS.has(normToken(v)); }
export function isValidClientName(v) { const s = String(v ?? "").trim(); if (!s || isDocToken(s) || /^\d+$/.test(s)) return false; return /[A-Za-zÀ-ÿ]/.test(s) && s.replace(/[^A-Za-zÀ-ÿ]/g, "").length >= 2; }
export function pick(row, names) { for (const n of names) if (row[n] != null && String(row[n]).trim() !== "") return row[n]; return ""; }
export function detectSrc(fn) { const u = String(fn || "").toUpperCase().replace(/[\s\-_]/g, ""); return (u.includes("7007") || u.includes("CONSCAREB") || u.includes("RPTEB") || /EB\.XLS/.test(u)) ? "RPT_7007_CONS_CAR_EB" : "FINR1253"; }
export function calcFin(valor, venc) { const orig = num(valor); const dias = diffDias(venc); if (dias <= 0) return { valorOriginal: orig, valorMulta: 0, valorJuros: 0, valorTotalDebito: orig, diasAtraso: 0 }; const multa = orig * 0.02; const juros = (orig * 0.0033 * dias); return { valorOriginal: orig, valorMulta: multa, valorJuros: juros, valorTotalDebito: orig + multa + juros, diasAtraso: dias }; }
export function keyPart(v) { return String(v ?? "").toUpperCase().replace(INVISIBLE_DEDUPE, "").replace(/\s+/g, "").replace(/\./g, "").replace(/^0+(\d+)$/, "$1"); }
export function normalizeTituloNumero(titulo) { const raw = String(titulo ?? "").trim().replace(/\./g, ""); const m = raw.match(/^(.+?)\/(\d{1,4})$/); if (m) return { base: m[1].replace(/^0+(\d)/, "$1"), seq: m[2] }; return { base: raw, seq: "1" }; }
function displayTituloNumero(titulo) { return String(titulo ?? "").replace(INVISIBLE_DEDUPE, ""); }
function invisibleClientSuffix(item = {}) { const key = String(item.nrCli || item.client_code || item.nomeCli || item.client_name || "").replace(/\s+/g, "").toUpperCase(); if (!key) return ""; let suffix = ""; for (const c of key) suffix += `\u200B${c}`; return suffix; }
function titleWithClientSuffix(title, item) { const raw = String(title ?? ""); if (!raw || INVISIBLE_DEDUPE.test(raw)) return raw; INVISIBLE_DEDUPE.lastIndex = 0; return `${raw}${invisibleClientSuffix(item)}`; }
export function normalizarRazaoSocial(nome) { return String(nome || "").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[.,\-/\\]/g, " ").replace(/\b(LTDA|ME|EPP|S A|SA|EIRELI|SIMPLES|LTDA ME|ME LTDA)\b/g, "").replace(/\s+/g, " ").trim(); }
export function getClienteGroupKeyRPT7007(item) { const nome = normalizarRazaoSocial(item?.nomeCli || item?.client_name); if (nome.length >= 3) return `NOME:${nome}`; const cod = String(item?.nrCli || item?.client_code || "").replace(/\D/g, "").replace(/^0+(\d+)$/, "$1"); if (cod) return `COD:${cod}`; return ""; }
function extractClienteNomeAgrupamento(v) { const raw = String(v || "").trim(); const m = raw.match(/^(\d{1,10})\s*[\/\-\u2013]\s*(.{2,})$/); if (m && /[A-Za-zÀ-ÿ]/.test(m[2])) return m[2].trim(); return ""; }
export function getClienteAgrupamentoKey(item = {}) { const doc = String(item.cpfCnpj || item.cpf_cnpj || item.document || "").replace(/\D/g, ""); if (doc.length >= 11) return `DOC:${doc}`; const nomeExtraido = extractClienteNomeAgrupamento(item.nomeCli || item.client_name || ""); if (nomeExtraido) return `NOME:${normalizarRazaoSocial(nomeExtraido)}`; const nome = normalizarRazaoSocial(item.nomeCli || item.client_name || ""); if (nome.length >= 3) return `NOME:${nome}`; return ""; }
export function isSystemGeneratedUser(user) { const u = normText(user); return u.includes("SISTEMA") || u.includes("IMPORTACAO"); }
export function manualObservationText(obs, user) { const text = String(obs || "").trim(); if (!text || isSystemGeneratedUser(user)) return ""; return text; }
function normalizeKeyDate(v) { const iso = dateISO(v); return iso ? iso.replace(/-/g, "") : ""; }
export function getTituloKey(item = {}) { const origem = item.origem ?? item.source; const cliente = item.nrCli ?? item.client_code ?? item["Código Cliente"] ?? item.nomeCli ?? item.client_name ?? ""; const tipo = item.tp ?? item.doc_type ?? ""; const tituloRaw = item.titulo ?? item.title_number ?? item["Número Documento"] ?? ""; const { base: tituloBase, seq: seqFromTitulo } = normalizeTituloNumero(tituloRaw); const seq = (item.seq ?? item["Sequência"] ?? "") || seqFromTitulo; const vencimento = item.vencimento ?? item.due_date ?? ""; return [keyPart(origem), keyPart(cliente), keyPart(tipo), keyPart(tituloBase), keyPart(seq), normalizeKeyDate(vencimento)].filter(Boolean).join("|"); }
export function dedupeTitulos(items) { const map = new Map(); for (const item of items || []) { const key = getTituloKey(item); const prev = map.get(key); if (!prev) { map.set(key, item); continue; } const sc = (r) => (String(r.obs ?? r.last_note ?? "").trim() ? 2 : 0) + ((r.dataPromessa ?? r.promise_date) ? 2 : 0) + ((r.dataContato ?? r.last_contact_date) ? 1 : 0) + (Number(r.qtd ?? r.contact_count) > 0 ? 1 : 0) + ((r.status ?? r.current_status) && (r.status ?? r.current_status) !== "Não Contatado" ? 1 : 0) + (["pago_importacao", "sem_carteira"].includes(r.workflow_status) ? -100 : 0); const sr = sc(item), sp = sc(prev); if (sr > sp) map.set(key, item); } return Array.from(map.values()); }
export function buildId({ origem, nrCli, tp, titulo, seq }) { return [origem, nrCli, tp, displayTituloNumero(titulo), seq].map(keyPart).join("|"); }
export function cliKey(item) { return `${String(item.nrCli || "").trim()}||${normText(item.nomeCli || "")}`; }

function origemExibicaoCarteira(source) { return source === "RPT_E_FINR" ? "FINR1253" : source; }
function normalizeWorkflowStatusForCarteira(status) { return String(status || "").trim() === "sem_carteira" ? "" : status; }
export function buildItem(o) { const valorOriginal = num(o.valorOriginal ?? o.original_value ?? 0); const valorRecebido = num(o.valorRecebido ?? o.received_value ?? 0); const saldoErp = num(o.saldoErp ?? o.erp_balance ?? 0); const valorEmAberto = num(o.valorEmAberto ?? o.open_value ?? saldoErp ?? Math.max(0, valorOriginal - valorRecebido)); const cFin = calcFin(valorEmAberto, o.vencimento ?? o.due_date); const workflowOriginal = o.encaminhar ?? o.workflow_status ?? ""; const workflowNormalizado = normalizeWorkflowStatusForCarteira(workflowOriginal); return { id: o._dbId || o.id || Math.random(), _dbId: o._dbId || o.id, origem: origemExibicaoCarteira(o.origem ?? o.source ?? ""), nrCli: o.nrCli ?? o.client_code ?? "", nomeCli: o.nomeCli ?? o.client_name ?? "", titulo: o.titulo ?? o.title_number ?? "", seq: o.seq ?? o["Sequência"] ?? "", tp: o.tp ?? o.doc_type ?? "", ser: o.ser ?? o.serie ?? "", nfServico: o.nfServico ?? o.nf_servico ?? "", emissao: o.emissao ?? o.issue_date ?? "", vencimento: o.vencimento ?? o.due_date ?? "", valorOriginal, valorRecebido, valorEmAberto: cFin.valorTotalDebito, valorMulta: cFin.valorMulta, valorJuros: cFin.valorJuros, valorTotalDebito: cFin.valorTotalDebito, diasAtraso: cFin.diasAtraso, qtd: o.qtd ?? o.contact_count ?? 0, status: o.status ?? o.current_status ?? "Não Contatado", dataContato: o.dataContato ?? o.last_contact_date ?? "", dataPromessa: o.dataPromessa ?? o.promise_date ?? "", encaminhar: workflowNormalizado, workflow_status: workflowNormalizado, workflow_status_diagnostico: workflowOriginal, obs: manualObservationText(o.obs ?? o.last_note ?? "", o.usuario ?? o.updated_by ?? ""), usuario: o.usuario ?? o.updated_by ?? "", solicitanteProtesto: o.solicitanteProtesto ?? o.protest_requested_by ?? "", clientCategory: o.clientCategory ?? o.client_category ?? "", clientGroupKey: o.clientGroupKey ?? o.client_group_key ?? "", updated_by: o.updated_by, portador: o.portador ?? "", erpClientCodes: o.erpClientCodes ?? o.erp_client_codes ?? [] }; }
export function dbToItem(r) { return buildItem({ _dbId: r.id, origem: origemExibicaoCarteira(r.source), nrCli: r.client_code, nomeCli: r.client_name, clientGroupKey: r.client_group_key || "", primaryClientCode: r.primary_client_code || "", erpClientCodes: r.erp_client_codes || [], titulo: r.title_number, seq: r.seq, tp: r.doc_type, ser: r.serie, nfServico: r.nf_servico, emissao: r.issue_date, vencimento: r.due_date, valorOriginal: r.original_value, valorRecebido: r.received_value, valorEmAberto: r.open_value, saldoErp: r.erp_balance, status: r.current_status, dataContato: r.last_contact_date, dataPromessa: r.promise_date, encaminhar: r.workflow_status, workflow_status: r.workflow_status, obs: r.last_note, usuario: r.updated_by, solicitanteProtesto: r.protest_requested_by, qtd: r.contact_count, clientCategory: r.client_category, portador: r.portador }); }
function cleanClientCode(v) { return String(v ?? "").replace(/\D/g, "").trim(); }
function cellText(row, idx) { return String((row || [])[idx] ?? "").trim(); }
function joinedRow(row) { return (row || []).map((c) => String(c ?? "").trim()).filter(Boolean).join(" "); }
function parseClienteLinha(row) { const raw = cellText(row, 0); const m = raw.match(/^Cliente:\s*([\d.]+)\s*-\s*(.+?)(?:\s*-\s*CPF\/CNPJ:\s*([\d./-]+))?\s*$/i); if (!m) return null; return { nrCli: cleanClientCode(m[1]), nomeCli: m[2], cpfCnpj: m[3] || "" }; }
function parseTotalCliente(row) { const raw = joinedRow(row); return { telefone: String(raw.match(/(?:Tel\.?|Telefone)\s*:?\s*(.+?)(?:\s+Contato\s*:|$)/i)?.[1] || "").trim(), contato: String(raw.match(/Contato\s*:?\s*(.+?)$/i)?.[1] || "").trim() }; }
function buildFinr1253ItemFromTitulo(row, clienteAtivo, dadosTotal = {}) { const tp = cellText(row, 0).toUpperCase(); if (!clienteAtivo || !isValidClientName(clienteAtivo.nomeCli) || !isFinr1253TitleToken(tp)) return null; const nDoc = cellText(row, 1); const seq = cellText(row, 2); const emissao = dateISO(cellText(row, 3)) || ""; const vencimento = dateISO(cellText(row, 4)) || ""; const vOriginal = num(cellText(row, 5)); const vRecebido = num(cellText(row, 6)); return { origem: "FINR1253", nrCli: clienteAtivo.nrCli, nomeCli: clienteAtivo.nomeCli, cpfCnpj: clienteAtivo.cpfCnpj, tp, titulo: nDoc, seq, emissao, vencimento, valorOriginal: vOriginal, valorRecebido: vRecebido, valorEmAberto: Math.max(0, vOriginal - vRecebido) }; }
export function parseRows1253(rows) { if (!Array.isArray(rows) || rows.length === 0) return []; const items = []; let clienteAtivo = null; let bufferTitulos = []; const flushBloco = (dadosTotal = {}) => { for (const row of bufferTitulos) { const item = buildFinr1253ItemFromTitulo(row, clienteAtivo, dadosTotal); if (item) items.push(item); } bufferTitulos = []; }; for (const row of rows) { const raiz = cellText(row, 0); if (!raiz) continue; const isCliente = raiz.toLowerCase().startsWith("cliente:"); if (isCliente) { flushBloco(); clienteAtivo = parseClienteLinha(row); } else if (raiz.toLowerCase().startsWith("total")) { flushBloco(parseTotalCliente(row)); clienteAtivo = null; } else if (clienteAtivo) { bufferTitulos.push(row); } } flushBloco(); return items; }
const H7007 = { nomeCli: ["NOMCLI", "NOME CLIENTE", "RAZAO SOCIAL", "CLIENTE", "SACADO", "NOME SACADO", "DEVEDOR", "NOME", "RAZAO", "NOME DO CLIENTE", "FAVORECIDO"], nrCli: ["CODCLI", "COD CLIENTE", "CODIGO CLIENTE", "CODIGO", "COD", "CÓDIGO", "CÓDIGO CLIENTE", "CÓDIGO SACADO", "NÚMERO DO CLIENTE", "CÓDIGO DEVEDOR"], tp: ["TIPO DOCUMENTO", "TIPO DOC", "DOC", "TIPO", "TIPO_DOC", "TIPO_DOCUMENTO", "TIPO DOCUMENTO"], titulo: ["NUMERO DOCUMENTO", "NÚMERO DOCUMENTO", "NUM DOC", "NÚMERO DOC", "NUMERO DOC", "DOCUMENTO", "Nº DOC", "NÚMERO_DOCUMENTO", "N_DOCUMENTO", "TITULO", "NÚMERO TÍTULO", "NUMERO TITULO"], seq: ["SEQUENCIA", "SEQUÊNCIA", "SEQÜÊNCIA", "SEQ"], vencimento: ["VENCIMENTO", "DATA VENCIMENTO", "DT VENCIMENTO", "VENCIMENTO TITULO", "VENCIMENTO_TITULO"], emissao: ["EMISSAO", "EMISSÃO", "DATA EMISSAO", "DATA EMISSÃO", "DT EMISSAO", "DATA DOCUMENTO", "DATA DOC", "EMISSAO_TITULO"], valorOriginal: ["VALOR", "VALOR ORIGINAL", "VALOR NOTA FISCAL", "VALOR TITULO", "VALOR_TITULO", "VALOR_ORIGINAL", "VL ORIGINAL", "VL NOTA"], valorRecebido: ["RECEBIDO", "VALOR RECEBIDO", "VALOR PAGO", "VL RECEBIDO", "VL PAGO", "RECEBIMENTO"], portador: ["PORTADOR", "BANCO", "AGENCIA", "CODIGO PORTADOR", "CÓDIGO PORTADOR"], nfServico: ["NF SERVICO", "NF SERVIÇO", "NFE SERVICO", "NUMERO NF", "NUMERO NFSE", "NFSE"] };
function countHeaderMatches7007(values) { let matches = 0; for (const value of values || []) { const n = normH(value); for (const aliases of Object.values(H7007)) if (aliases.some((a) => normH(a) === n)) matches++; } return matches; }
function buildHeaderMap7007(sampleRow) { const map = {}; const keys = Object.keys(sampleRow || {}); for (const [field, aliases] of Object.entries(H7007)) { for (const realKey of keys) { const n = normH(realKey); if (aliases.some((a) => normH(a) === n)) { map[field] = realKey; break; } } } return map; }
function buildHeaderMap7007FromValues(sampleRow) { const map = {}; const keys = Object.keys(sampleRow || {}); for (const [field, aliases] of Object.entries(H7007)) { for (const realKey of keys) { const n = normH(realKey); if (aliases.some((a) => normH(a) === n)) { map[field] = realKey; break; } } } return map; }
function detectHeaderRow7007(rows) { for (let i = 0; i < Math.min(rows.length, 20); i += 1) { const row = rows[i]; if (!row || typeof row !== "object") continue; if (countHeaderMatches7007(Object.keys(row || {})) >= 3) return i; } return 0; }
export function parseRows7007(rows) { if (!Array.isArray(rows) || rows.length === 0) return []; const headerMap = buildHeaderMap7007(rows[0]); const items = []; for (let i = 0; i < rows.length; i++) { const row = rows[i]; if (!row || typeof row !== "object") continue; const nomeCli = pick(row, [headerMap.nomeCli, "NOME CLIENTE", "CLIENTE", "Razão Social", "Nome"].filter(Boolean)) || ""; const nrCli = pick(row, [headerMap.nrCli, "CODIGO CLIENTE", "Código Cliente", "Código", "Código do Cliente"].filter(Boolean)) || ""; const tp = pick(row, [headerMap.tp, "TIPO DOCUMENTO", "Tipo Documento"].filter(Boolean)) || ""; const titulo = pick(row, [headerMap.titulo, "NUMERO DOCUMENTO", "Número Documento", "Número", "Número Título"].filter(Boolean)) || ""; const seq = pick(row, [headerMap.seq, "SEQUENCIA", "Sequência"].filter(Boolean)) || ""; const vencimento = dateISO(pick(row, [headerMap.vencimento, "VENCIMENTO", "Data Vencimento"].filter(Boolean)) || "") || ""; const emissao = dateISO(pick(row, [headerMap.emissao, "EMISSAO", "Data Emissão"].filter(Boolean)) || "") || ""; const valorOriginal = num(pick(row, [headerMap.valorOriginal, "VALOR ORIGINAL", "Valor", "VL ORIGINAL"].filter(Boolean)) || 0); const valorRecebido = num(pick(row, [headerMap.valorRecebido, "VALOR RECEBIDO", "Valor Recebido", "VL RECEBIDO"].filter(Boolean)) || 0); const portador = pick(row, [headerMap.portador, "PORTADOR", "Portador", "Banco"].filter(Boolean)) || ""; const nfServico = pick(row, [headerMap.nfServico, "NF SERVICO", "NF Serviço"].filter(Boolean)) || ""; if (!nomeCli && !nrCli) continue; if (!isValidClientName(nomeCli) && !nrCli) continue; items.push({ origem: "RPT_7007_CONS_CAR_EB", nrCli, nomeCli, tp, titulo, seq, vencimento, emissao, valorOriginal, valorRecebido, valorEmAberto: Math.max(0, valorOriginal - valorRecebido), portador, nfServico }); } return items; }
export function dlCsv(name, rows) { const ws = XLSX.utils.json_to_sheet(rows); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Dados"); XLSX.writeFile(wb, name); }
export function openPrint() { window.print(); }
